### ISSUE TITLE
Slugs

### ISSUE THREAD

**Issue by codewithcheese** [product-os/contrato#44]
A `slug` is formatted using the `loop`, `type` and `handle` fields of a contract.

If the _contract loop and the type loop is null_ then a slug is formatted with just the type and handle: `<type>/<handle>`

If the _contract loop is **not** null_ and the _type loop is null_ then a slug is formatted with all three fields `<loop>/<type>/<handle>`

If the _contract loop is **not** null_ and the _type loop is **not** null_ then the `type` is prefixed with `@` to indicate that the contract and type belong to the loop `<loop>/@<type>/<slug>`

A slug can only reference a type in the null loop or contract loop. If the type belongs to a different loop than the contract loop the type must be imported. A type can be imported using a type contract that references another type, this has not been fully fleshed out yet.

### Open questions
 - Should version be part of the slug?
 - Should the separator be `/`?
 - Should the @ symbol prefix the type of the whole slug?

**Comment by Hades32** [comment]
Another question:
We want to support nested loops, but would the handles of those loops still need to be globally unique?
I would be in favor of this and e.g. enforcing by convention that nested loops' handles are simply prefixed by their parent loop's handle. Otherwise we would need to support `loop/sub-loop/sub-sub-loop/@type/handle` slugs... 

About the @ placement:
We could also move to `type/loop/handle` then the two options would be the same.

I like the `/`, but if we use `.` then we should switch order (like DNS) to be `handle.loop.type`.

I'm adding some examples to the rules you laid out:
```yaml
handle: broken-sd-card
type: pattern
```
Would become `pattern/broken-sd-card`
```yaml
handle: slow-ui
type: pattern
loop: product-os
```
Would become `product-os/pattern/slow-ui`
```yaml
handle: the-one-with-the-open-fleets
type: release-party
loop: balena-io
---
type: type
slug: release-party
type-reference:
    loop: balena-ltd
    type: release-party
```
Would become `balena-io/@release-party/the-one-with-the-open-fleets`
